'use client';

import { useState, useRef, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { DEMO_ALERTS, DEMO_CASES, DEMO_RISK_SCORES, DEMO_KPIS, DEMO_RISK_DISTRIBUTION, DEMO_SIGNAL_STATS, DEMO_AUDIT_LOGS, TFCU_TENANT, IC3_THREAT_DATA, DEMO_VENDOR_RISKS } from '@/lib/demo-data';

type ReportType = 'executive' | 'alert' | 'case' | 'sar' | 'audit' | 'risk' | 'ic3_threat';

export default function ReportsPage() {
  return (
    <Suspense fallback={<div className="p-8 text-gray-500">Loading reports...</div>}>
      <ReportsContent />
    </Suspense>
  );
}

function ReportsContent() {
  const searchParams = useSearchParams();
  const initialType = (searchParams.get('type') as ReportType) ?? 'executive';
  const [reportType, setReportType] = useState<ReportType>(initialType);
  const reportRef = useRef<HTMLDivElement>(null);

  function handlePrint() {
    window.print();
  }

  function handleDownloadHTML() {
    if (!reportRef.current) return;
    const html = `<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>RiskRadar Report — ${TFCU_TENANT.name}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 40px; color: #1a1a1a; font-size: 14px; line-height: 1.6; }
  h1 { font-size: 24px; border-bottom: 3px solid #2563eb; padding-bottom: 8px; }
  h2 { font-size: 18px; color: #1e40af; margin-top: 32px; }
  h3 { font-size: 15px; color: #374151; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; font-size: 13px; }
  th { background: #f3f4f6; font-weight: 600; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
  .critical { background: #fef2f2; color: #991b1b; }
  .high { background: #fff7ed; color: #9a3412; }
  .medium { background: #fefce8; color: #854d0e; }
  .low { background: #f0fdf4; color: #166534; }
  .meta { color: #6b7280; font-size: 12px; }
  .section { margin: 24px 0; padding: 16px; background: #f9fafb; border-radius: 8px; border: 1px solid #e5e7eb; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; }
  @media print { body { padding: 20px; } }
</style>
</head><body>${reportRef.current.innerHTML}
<div class="footer">
  <p>Generated by RiskRadar | ${TFCU_TENANT.name} | ${new Date().toLocaleString()} | CONFIDENTIAL — For authorized recipients only</p>
</div>
</body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `riskradar-${reportType}-report-${new Date().toISOString().split('T')[0]}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div>
      {/* Controls — hidden in print */}
      <div className="print:hidden">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
          <div className="flex gap-2">
            <button onClick={handlePrint} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">
              Print / Save as PDF
            </button>
            <button onClick={handleDownloadHTML} className="px-4 py-2 bg-gray-700 text-white rounded-lg text-sm font-medium hover:bg-gray-800">
              Download Report
            </button>
          </div>
        </div>

        <div className="flex gap-2 mb-6">
          {([
            ['executive', 'Executive Summary'],
            ['ic3_threat', 'IC3 Threat Brief'],
            ['alert', 'Alert Brief'],
            ['case', 'Case Report'],
            ['sar', 'SAR Draft'],
            ['risk', 'Risk Assessment'],
            ['audit', 'Audit Trail'],
          ] as [ReportType, string][]).map(([type, label]) => (
            <button
              key={type}
              onClick={() => setReportType(type)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                reportType === type
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* Report Content — print-optimized */}
      <div ref={reportRef} className="bg-white rounded-xl border border-gray-200 p-8 print:border-0 print:shadow-none print:p-0">
        {reportType === 'executive' && <ExecutiveSummaryReport />}
        {reportType === 'ic3_threat' && <IC3ThreatBriefReport />}
        {reportType === 'alert' && <AlertBriefReport />}
        {reportType === 'case' && <CaseReport />}
        {reportType === 'sar' && <SARDraftReport />}
        {reportType === 'risk' && <RiskAssessmentReport />}
        {reportType === 'audit' && <AuditTrailReport />}
      </div>
    </div>
  );
}

// ─── EXECUTIVE SUMMARY ─────────────────────────────────────
function ExecutiveSummaryReport() {
  const kpis = DEMO_KPIS;
  const dist = DEMO_RISK_DISTRIBUTION;
  const alerts = DEMO_ALERTS;
  const cases = DEMO_CASES;

  return (
    <div>
      <ReportHeader title="Executive Risk Summary" subtitle="Weekly Intelligence Brief" />

      <div className="grid grid-cols-4 gap-4 my-6">
        <MetricBox label="Active Alerts" value={String(kpis.activeAlerts.value)} change={kpis.activeAlerts.change} />
        <MetricBox label="Open Cases" value={String(kpis.openCases.value)} change={kpis.openCases.change} />
        <MetricBox label="High-Risk Subjects" value={String(kpis.highRiskSubjects.value)} change={kpis.highRiskSubjects.change} />
        <MetricBox label="Signals (24h)" value={kpis.signals24h.value} change={kpis.signals24h.change} />
      </div>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Risk Distribution</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Severity</th>
            <th className="text-left py-2">Count</th>
            <th className="text-left py-2">% of Total</th>
          </tr>
        </thead>
        <tbody>
          {Object.entries(dist).map(([sev, count]) => (
            <tr key={sev} className="border-b border-gray-100">
              <td className="py-2 capitalize font-medium">{sev}</td>
              <td className="py-2">{count}</td>
              <td className="py-2">{Math.round((count / 14) * 100)}%</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Critical & High Alerts Requiring Action</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">ID</th>
            <th className="text-left py-2">Alert</th>
            <th className="text-left py-2">Severity</th>
            <th className="text-left py-2">Score</th>
            <th className="text-left py-2">Status</th>
          </tr>
        </thead>
        <tbody>
          {alerts.filter((a) => a.severity === 'critical' || a.severity === 'high').map((a) => (
            <tr key={a.id} className="border-b border-gray-100">
              <td className="py-2 font-mono text-xs">{a.id}</td>
              <td className="py-2">{a.title}</td>
              <td className="py-2"><span className={`badge ${a.severity}`}>{a.severity}</span></td>
              <td className="py-2 font-bold">{a.compoundScore}</td>
              <td className="py-2">{a.status.replace(/_/g, ' ')}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Active Case Summary</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Case</th>
            <th className="text-left py-2">Priority</th>
            <th className="text-left py-2">Status</th>
            <th className="text-left py-2">SLA</th>
            <th className="text-left py-2">Assignee</th>
          </tr>
        </thead>
        <tbody>
          {cases.filter((c) => !c.status.startsWith('closed')).map((c) => (
            <tr key={c.id} className="border-b border-gray-100">
              <td className="py-2">
                <div className="font-mono text-xs">{c.id}</div>
                <div className="text-xs text-gray-500">{c.title}</div>
              </td>
              <td className="py-2"><span className={`badge ${c.priority}`}>{c.priority}</span></td>
              <td className="py-2">{c.status.replace(/_/g, ' ')}</td>
              <td className="py-2"><span className={c.slaStatus === 'breached' ? 'text-red-600 font-bold' : ''}>{c.slaStatus.replace(/_/g, ' ')}</span></td>
              <td className="py-2">{c.assignee}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Recommendations</h2>
      <ol className="list-decimal list-inside space-y-2 text-sm text-gray-700">
        <li><strong>Immediate:</strong> Review and action critical alert ALT-2026-1201 (insider transaction fraud pattern — score 89). Suspend override privileges for MSR-4821 pending investigation.</li>
        <li><strong>Within 24h:</strong> Rotate credentials for SVCACCT-CORE following geographic anomaly detection. Conduct blast radius assessment.</li>
        <li><strong>Within 72h:</strong> BSA Officer review of Farmingville branch structuring pattern (14 overrides, sub-CTR clustering). Begin SAR assessment.</li>
        <li><strong>This Week:</strong> Complete overdue SLA for Case CSE-2026-004 (credential compromise). Schedule branch manager meeting for Farmingville investigation.</li>
      </ol>

      <ReportFooter />
    </div>
  );
}

// ─── ALERT BRIEF ────────────────────────────────────────────
function AlertBriefReport() {
  const alert = DEMO_ALERTS[0]!;
  const brief = alert.evidenceBrief!;

  return (
    <div>
      <ReportHeader title="Alert Intelligence Brief" subtitle={`Alert ${alert.id}`} />

      <div className="my-6 p-4 bg-red-50 border border-red-200 rounded-lg">
        <div className="flex items-center gap-3">
          <span className="badge critical text-sm">CRITICAL</span>
          <span className="font-bold text-lg">{alert.title}</span>
        </div>
        <p className="text-sm text-gray-700 mt-2">{alert.description}</p>
      </div>

      <div className="grid grid-cols-3 gap-4 my-6">
        <MetricBox label="Compound Score" value={String(alert.compoundScore)} />
        <MetricBox label="Confidence" value={String(alert.confidenceScore)} />
        <MetricBox label="FP Likelihood" value={alert.falsePositiveLikelihood} />
      </div>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Evidence Chain</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">#</th>
            <th className="text-left py-2">Timestamp</th>
            <th className="text-left py-2">Description</th>
            <th className="text-left py-2">Source</th>
            <th className="text-left py-2">Significance</th>
          </tr>
        </thead>
        <tbody>
          {brief.evidenceChain.map((e) => (
            <tr key={e.sequence} className="border-b border-gray-100">
              <td className="py-2 font-bold text-blue-600">{e.sequence}</td>
              <td className="py-2 text-xs font-mono">{new Date(e.timestamp).toLocaleString()}</td>
              <td className="py-2">{e.description}</td>
              <td className="py-2 text-xs font-mono">{e.sourceSystem}</td>
              <td className="py-2 text-xs">{e.significance}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">AI Reasoning</h2>
      <div className="p-4 bg-gray-50 border border-gray-200 rounded-lg text-sm leading-relaxed">
        <div className="text-xs text-purple-600 font-medium mb-2">Nemotron-Cascade-2 (Thinking Mode)</div>
        {brief.reasoning}
      </div>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Regulatory Mapping</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Regulation</th>
            <th className="text-left py-2">Section</th>
            <th className="text-left py-2">Description</th>
            <th className="text-left py-2">Relevance</th>
          </tr>
        </thead>
        <tbody>
          {brief.regulatoryMapping.map((r, i) => (
            <tr key={i} className="border-b border-gray-100">
              <td className="py-2 font-medium">{r.regulation}</td>
              <td className="py-2 font-mono text-xs">{r.section}</td>
              <td className="py-2">{r.description}</td>
              <td className="py-2"><span className={`badge ${r.relevance === 'direct' ? 'critical' : 'medium'}`}>{r.relevance}</span></td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Recommended Actions</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Priority</th>
            <th className="text-left py-2">Action</th>
          </tr>
        </thead>
        <tbody>
          {brief.recommendedActions.map((a, i) => (
            <tr key={i} className="border-b border-gray-100">
              <td className="py-2"><span className={`badge ${a.priority === 'immediate' ? 'critical' : a.priority === 'within_24h' ? 'high' : 'medium'}`}>{a.priority.replace(/_/g, ' ')}</span></td>
              <td className="py-2">{a.action}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <ReportFooter />
    </div>
  );
}

// ─── SAR DRAFT ──────────────────────────────────────────────
function SARDraftReport() {
  const alert = DEMO_ALERTS[0]!;
  const brief = alert.evidenceBrief!;

  return (
    <div>
      <ReportHeader title="Suspicious Activity Report — DRAFT" subtitle="FinCEN Form 111 Narrative Section" />

      <div className="my-6 p-4 bg-yellow-50 border border-yellow-300 rounded-lg text-sm">
        <strong>DRAFT — FOR INTERNAL REVIEW ONLY.</strong> This auto-generated SAR narrative requires BSA Officer review and approval before filing.
        Filing deadline: <strong>April 27, 2026</strong> (30 days from detection).
      </div>

      <h2 className="text-lg font-bold text-gray-900 mt-6 mb-3">Subject Information</h2>
      <table className="w-full border-collapse text-sm">
        <tbody>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium w-48">Subject ID</td><td className="py-2">MSR-4821</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Role</td><td className="py-2">Teller Supervisor — Hauppauge Branch</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Institution</td><td className="py-2">Teachers Federal Credit Union (RSSD: XXXXXXX)</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Filing Type</td><td className="py-2">Initial SAR — Insider Abuse / BSA Violations</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Activity Date Range</td><td className="py-2">March 20, 2026 — March 28, 2026</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Total Amount</td><td className="py-2">$340,000.00</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Detection Method</td><td className="py-2">RiskRadar AI — Compound Risk Fusion (Score: 89/100)</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Detection Date</td><td className="py-2">March 28, 2026</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Filing Deadline</td><td className="py-2 font-bold text-red-600">April 27, 2026</td></tr>
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Narrative</h2>
      <div className="p-4 bg-gray-50 border border-gray-200 rounded-lg text-sm leading-relaxed space-y-4">
        <p>On March 28, 2026, Teachers Federal Credit Union&apos;s automated risk monitoring system (RiskRadar) identified a compound risk pattern involving a Teller Supervisor at the Hauppauge branch location (Subject MSR-4821). The system detected the convergence of multiple suspicious indicators across financial transaction, security access, and human resources data domains.</p>

        <p><strong>Transaction Activity:</strong> Between March 27-28, 2026, the subject processed seven (7) wire transfer overrides totaling approximately $340,000. Four transfers exceeded $25,000 each. These transactions were processed using manager override authority during a period when the subject&apos;s direct supervisor (Branch Manager) was on approved PTO (March 27-31, 2026). The override volume was approximately 7 times the subject&apos;s monthly baseline.</p>

        <p><strong>Beneficiary Accounts:</strong> Two of the three receiving beneficiary accounts (BEN-A1104 and BEN-A1105) were created on the same day as the largest transfers ($85,000 and $92,000 respectively). The proximity of new beneficiary account creation to large outbound wire transfers is consistent with structuring indicators.</p>

        <p><strong>After-Hours Access:</strong> On March 27, 2026, at approximately 10:14 PM, the subject accessed twelve (12) member profiles in the institution&apos;s CRM system. None of these profiles were associated with active service requests or open cases. This access occurred outside normal branch business hours (8:30 AM - 5:00 PM).</p>

        <p><strong>Compliance Training:</strong> The subject was overdue on mandatory annual BSA/AML compliance training, which was due March 15, 2026.</p>

        <p><strong>Risk Assessment:</strong> The automated risk analysis system assigned a compound risk score of 89/100 with 91% confidence and a low false-positive likelihood. The pattern matches FinCEN Advisory 2025-A003 insider threat red flag indicators 4 (override clustering), 7 (supervisor absence correlation), and 12 (new payee creation proximate to transfers).</p>

        <p>This SAR is being filed in accordance with 31 CFR 1020.320 and NCUA Letter 26-CU-03. The institution has taken the following immediate actions: (1) suspended override privileges for the subject, (2) placed administrative holds on the newly created beneficiary accounts, and (3) initiated a full 90-day transaction review.</p>
      </div>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Supporting Evidence Citations</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Evidence #</th>
            <th className="text-left py-2">Source System</th>
            <th className="text-left py-2">Reference ID</th>
            <th className="text-left py-2">Description</th>
          </tr>
        </thead>
        <tbody>
          {brief.evidenceChain.map((e) => (
            <tr key={e.sequence} className="border-b border-gray-100">
              <td className="py-2 font-bold">{e.sequence}</td>
              <td className="py-2 font-mono text-xs">{e.sourceSystem}</td>
              <td className="py-2 font-mono text-xs">{e.sourceId}</td>
              <td className="py-2">{e.description}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Regulatory References</h2>
      <ul className="list-disc list-inside text-sm space-y-1 text-gray-700">
        {brief.regulatoryMapping.map((r, i) => (
          <li key={i}><strong>{r.regulation} — {r.section}:</strong> {r.description}</li>
        ))}
      </ul>

      <div className="mt-8 p-4 border-2 border-gray-300 rounded-lg">
        <h3 className="font-bold text-sm mb-3">Approval Signatures</h3>
        <div className="grid grid-cols-2 gap-8 text-sm">
          <div>
            <div className="border-b border-gray-400 h-12 mb-1" />
            <div className="text-xs text-gray-500">BSA Officer — David Chen</div>
            <div className="text-xs text-gray-400">Date: _______________</div>
          </div>
          <div>
            <div className="border-b border-gray-400 h-12 mb-1" />
            <div className="text-xs text-gray-500">VP of Risk & Compliance — Maria Gonzalez</div>
            <div className="text-xs text-gray-400">Date: _______________</div>
          </div>
        </div>
      </div>

      <ReportFooter classification="CONFIDENTIAL — SAR DISCLOSURE PROHIBITED (31 USC 5318(g)(2))" />
    </div>
  );
}

// ─── CASE REPORT ────────────────────────────────────────────
function CaseReport() {
  const caseData = DEMO_CASES[0]!;

  return (
    <div>
      <ReportHeader title="Case Investigation Report" subtitle={`Case ${caseData.id}`} />

      <div className="my-6 grid grid-cols-2 gap-4">
        <div>
          <h3 className="text-xs text-gray-500 uppercase mb-1">Case Title</h3>
          <p className="font-medium">{caseData.title}</p>
        </div>
        <div>
          <h3 className="text-xs text-gray-500 uppercase mb-1">Priority</h3>
          <span className={`badge ${caseData.priority}`}>{caseData.priority}</span>
        </div>
      </div>

      <table className="w-full border-collapse text-sm my-4">
        <tbody>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium w-48">Case ID</td><td className="py-2">{caseData.id}</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Status</td><td className="py-2">{caseData.status.replace(/_/g, ' ')}</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Subject</td><td className="py-2">{caseData.subjectId}</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Assigned To</td><td className="py-2">{caseData.assignee}</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">Associated Alerts</td><td className="py-2">{caseData.alerts}</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">SLA Deadline</td><td className="py-2">{caseData.slaDeadline}</td></tr>
          <tr className="border-b border-gray-100"><td className="py-2 font-medium">SLA Status</td><td className="py-2"><span className={caseData.slaStatus === 'breached' ? 'text-red-600 font-bold' : ''}>{caseData.slaStatus.replace(/_/g, ' ')}</span></td></tr>
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Description</h2>
      <p className="text-sm text-gray-700 leading-relaxed">{caseData.description}</p>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Investigation Timeline</h2>
      <div className="text-sm text-gray-500 italic">Investigation notes and timeline entries would be populated from the case management system.</div>

      <ReportFooter />
    </div>
  );
}

// ─── RISK ASSESSMENT ────────────────────────────────────────
function RiskAssessmentReport() {
  const scores = DEMO_RISK_SCORES;
  const signals = DEMO_SIGNAL_STATS;

  return (
    <div>
      <ReportHeader title="Organizational Risk Assessment" subtitle="Monthly Risk Posture Review" />

      <h2 className="text-lg font-bold text-gray-900 mt-6 mb-3">Signal Activity (24h Snapshot)</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Domain</th>
            <th className="text-left py-2">Signal Count</th>
            <th className="text-left py-2">% of Total</th>
          </tr>
        </thead>
        <tbody>
          {Object.entries(signals.byDomain).map(([domain, count]) => (
            <tr key={domain} className="border-b border-gray-100">
              <td className="py-2 capitalize font-medium">{domain}</td>
              <td className="py-2">{count}</td>
              <td className="py-2">{Math.round((count / signals.total24h) * 100)}%</td>
            </tr>
          ))}
          <tr className="border-t-2 border-gray-300 font-bold">
            <td className="py-2">Total</td>
            <td className="py-2">{signals.total24h.toLocaleString()}</td>
            <td className="py-2">100%</td>
          </tr>
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Subject Risk Scores</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Subject</th>
            <th className="text-left py-2">Type</th>
            <th className="text-left py-2">Department</th>
            <th className="text-left py-2">Score</th>
            <th className="text-left py-2">Trajectory</th>
            <th className="text-left py-2">30d Change</th>
          </tr>
        </thead>
        <tbody>
          {scores.map((s) => (
            <tr key={s.id} className="border-b border-gray-100">
              <td className="py-2 font-mono">{s.id}</td>
              <td className="py-2">{s.type}</td>
              <td className="py-2">{s.dept}</td>
              <td className="py-2 font-bold"><span className={`badge ${s.score >= 75 ? 'critical' : s.score >= 50 ? 'high' : s.score >= 25 ? 'medium' : 'low'}`}>{s.score}</span></td>
              <td className="py-2">{s.trajectory}</td>
              <td className="py-2 font-medium">{s.change}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <ReportFooter />
    </div>
  );
}

// ─── AUDIT TRAIL ────────────────────────────────────────────
function AuditTrailReport() {
  const logs = DEMO_AUDIT_LOGS;

  return (
    <div>
      <ReportHeader title="Audit Trail Export" subtitle="System Activity Log" />

      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Timestamp</th>
            <th className="text-left py-2">Actor</th>
            <th className="text-left py-2">Action</th>
            <th className="text-left py-2">Resource</th>
            <th className="text-left py-2">Details</th>
          </tr>
        </thead>
        <tbody>
          {logs.map((log) => (
            <tr key={log.id} className="border-b border-gray-100">
              <td className="py-2 text-xs font-mono">{new Date(log.timestamp).toLocaleString()}</td>
              <td className="py-2">{log.actor}</td>
              <td className="py-2 font-mono text-xs">{log.action}</td>
              <td className="py-2">{log.resource}</td>
              <td className="py-2 text-xs">{log.details}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <ReportFooter />
    </div>
  );
}

// ─── IC3 THREAT BRIEF ──────────────────────────────────────
function IC3ThreatBriefReport() {
  const ic3 = IC3_THREAT_DATA;
  const vendors = DEMO_VENDOR_RISKS;
  const ic3Alerts = DEMO_ALERTS.filter((a) =>
    a.domains.some((d: string) => ['crypto', 'bec', 'ai_threat', 'ransomware', 'vendor_risk'].includes(d))
  );

  return (
    <div>
      <ReportHeader title="FBI IC3 2025 Threat Intelligence Brief" subtitle="Organizational Exposure Assessment" />

      <div className="my-6 p-4 bg-blue-50 border border-blue-200 rounded-lg text-sm">
        <strong>Source:</strong> FBI Internet Crime Complaint Center (IC3) — 2025 Internet Crime Report.
        This brief maps the IC3&apos;s top threat categories to your organization&apos;s current risk posture and RiskRadar detection coverage.
      </div>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">IC3 2025 Headline Numbers</h2>
      <div className="grid grid-cols-3 gap-4 my-4">
        <MetricBox label="Total Complaints" value="1M+" />
        <MetricBox label="Total Losses" value="$20B+" />
        <MetricBox label="Your Coverage" value={`${ic3.organizationExposure.coveragePercentage}%`} />
      </div>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Top Threat Categories — Coverage Matrix</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Priority</th>
            <th className="text-left py-2">Threat Category</th>
            <th className="text-right py-2">Losses</th>
            <th className="text-right py-2">Complaints</th>
            <th className="text-center py-2">Trend</th>
            <th className="text-left py-2">RiskRadar Module</th>
            <th className="text-center py-2">Status</th>
          </tr>
        </thead>
        <tbody>
          {ic3.topThreats.map((threat) => (
            <tr key={threat.category} className="border-b border-gray-100">
              <td className="py-2"><span className={`badge ${threat.priority === 'P0' ? 'critical' : 'medium'}`}>{threat.priority}</span></td>
              <td className="py-2 font-medium">{threat.category}</td>
              <td className="py-2 text-right font-bold text-red-600">${(threat.losses / 1_000_000_000).toFixed(1)}B</td>
              <td className="py-2 text-right">{(threat.complaints / 1000).toFixed(0)}K</td>
              <td className="py-2 text-center text-sm">{threat.trend}</td>
              <td className="py-2">{threat.riskRadarModule}</td>
              <td className="py-2 text-center">
                <span className={`badge ${
                  threat.moduleStatus === 'active' ? 'low' :
                  threat.moduleStatus === 'partial' ? 'medium' : ''
                }`}>
                  {threat.moduleStatus === 'active' ? 'Active' : threat.moduleStatus === 'partial' ? 'Partial' : 'N/A'}
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Active IC3-Related Alerts</h2>
      {ic3Alerts.length > 0 ? (
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b-2 border-gray-300">
              <th className="text-left py-2">ID</th>
              <th className="text-left py-2">Alert</th>
              <th className="text-left py-2">Domains</th>
              <th className="text-left py-2">Severity</th>
              <th className="text-left py-2">Score</th>
            </tr>
          </thead>
          <tbody>
            {ic3Alerts.map((alert) => (
              <tr key={alert.id} className="border-b border-gray-100">
                <td className="py-2 font-mono text-xs">{alert.id}</td>
                <td className="py-2">{alert.title}</td>
                <td className="py-2 text-xs">{alert.domains.join(', ')}</td>
                <td className="py-2"><span className={`badge ${alert.severity}`}>{alert.severity}</span></td>
                <td className="py-2 font-bold">{alert.compoundScore}</td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p className="text-sm text-gray-500">No active IC3-related alerts.</p>
      )}

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Supply Chain Vendor Risk Assessment</h2>
      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="text-left py-2">Vendor</th>
            <th className="text-left py-2">Category</th>
            <th className="text-left py-2">Rating</th>
            <th className="text-left py-2">Risk Score</th>
            <th className="text-left py-2">Critical Findings</th>
            <th className="text-left py-2">Business Impact</th>
          </tr>
        </thead>
        <tbody>
          {vendors.map((v) => (
            <tr key={v.id} className="border-b border-gray-100">
              <td className="py-2 font-medium">{v.name}</td>
              <td className="py-2">{v.category}</td>
              <td className="py-2">
                {v.securityRating}
                {v.previousRating !== v.securityRating && (
                  <span className="text-red-500 text-xs ml-1">(was {v.previousRating})</span>
                )}
              </td>
              <td className="py-2 font-bold">{v.riskScore}</td>
              <td className="py-2">{v.criticalFindings}</td>
              <td className="py-2"><span className={`badge ${v.businessImpact === 'critical' ? 'critical' : v.businessImpact === 'high' ? 'high' : 'medium'}`}>{v.businessImpact}</span></td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">New Detection Modules Deployed</h2>
      <ol className="list-decimal list-inside space-y-2 text-sm text-gray-700">
        <li><strong>BEC Defense Suite:</strong> Email behavior analytics with writing style deviation detection, vendor impersonation monitoring, and payment verification workflows. Addresses $3B+ in BEC losses (IC3 #2 threat).</li>
        <li><strong>Crypto Fraud Radar:</strong> Wallet risk scoring via Chainalysis/TRM Labs integration, pig butchering pattern detection, mixer/sanctions screening. Addresses $8.6B investment fraud + $7.2B crypto fraud (IC3 #1 threat).</li>
        <li><strong>AI Threat Intelligence Feed:</strong> AI-generated phishing detection, deepfake tool tracking, LLM-crafted template fingerprinting. Addresses $893M AI-enabled scams (NEW IC3 category in 2025).</li>
        <li><strong>Ransomware Exposure Engine:</strong> Continuous attack surface scoring against MITRE ATT&CK TTPs, CVE-to-ransomware-group mapping, dark web intelligence. Addresses growing ransomware threat.</li>
        <li><strong>Supply Chain Risk Monitor:</strong> Vendor security posture scoring via SecurityScorecard, breach alerts, compliance tracking. Addresses cross-cutting supply chain risk vector.</li>
      </ol>

      <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">Recommendations</h2>
      <ol className="list-decimal list-inside space-y-2 text-sm text-gray-700">
        <li><strong>Immediate:</strong> Review BEC alert ALT-2026-1210 (CFO wire request — writing style deviation, score 92). Block wire transfer and verify out-of-band.</li>
        <li><strong>Immediate:</strong> Contact member MBR-9923 re: crypto pig butchering alert (ALT-2026-1212, score 81). Potential active fraud victim with $188K in transfers to high-risk wallet.</li>
        <li><strong>Within 24h:</strong> Patch 3 critical CVEs flagged by Ransomware Exposure Engine. Close exposed RDP ports on branch servers.</li>
        <li><strong>Within 72h:</strong> Review Acme Payments vendor risk (SecurityScorecard A→C drop, 2,400 leaked credentials). Acme processes 40% of ACH volume.</li>
        <li><strong>This Week:</strong> Deploy AI-generated phishing awareness brief to all staff. 47 AI-crafted spear-phishing emails detected targeting TFCU in past 72 hours.</li>
      </ol>

      <ReportFooter classification="CONFIDENTIAL — FBI IC3 Threat Intelligence Brief" />
    </div>
  );
}

// ─── SHARED COMPONENTS ──────────────────────────────────────
function ReportHeader({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="border-b-2 border-blue-600 pb-4 mb-6">
      <div className="flex items-center justify-between">
        <div>
          <div className="text-sm text-blue-600 font-semibold tracking-wider uppercase">RiskRadar Intelligence Platform</div>
          <h1 className="text-2xl font-bold text-gray-900 mt-1">{title}</h1>
          <div className="text-sm text-gray-500 mt-0.5">{subtitle}</div>
        </div>
        <div className="text-right text-sm">
          <div className="font-semibold text-gray-900">{TFCU_TENANT.name}</div>
          <div className="text-gray-500">{new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</div>
          <div className="text-xs text-gray-400 mt-1">Report ID: RPT-{Date.now().toString(36).toUpperCase()}</div>
        </div>
      </div>
    </div>
  );
}

function ReportFooter({ classification }: { classification?: string }) {
  return (
    <div className="mt-10 pt-4 border-t border-gray-200 text-xs text-gray-400">
      <div className="flex justify-between">
        <span>{classification ?? 'CONFIDENTIAL — For authorized recipients only'}</span>
        <span>Generated by RiskRadar v1.0 | {new Date().toLocaleString()}</span>
      </div>
      <div className="mt-1">{TFCU_TENANT.name} | Page 1 of 1</div>
    </div>
  );
}

function MetricBox({ label, value, change }: { label: string; value: string; change?: string }) {
  return (
    <div className="border border-gray-200 rounded-lg p-3 text-center">
      <div className="text-xs text-gray-500 uppercase">{label}</div>
      <div className="text-2xl font-bold text-gray-900">{value}</div>
      {change && <div className="text-xs text-red-500">{change} vs prior week</div>}
    </div>
  );
}
