steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'us-central1-docker.pkg.dev/amadds102025/riskradar/riskradar-api:v10'
      - '-t'
      - 'us-central1-docker.pkg.dev/amadds102025/riskradar/riskradar-api:latest'
      - '-f'
      - 'deploy/docker/Dockerfile.api'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/amadds102025/riskradar/riskradar-api:v10'
  - 'us-central1-docker.pkg.dev/amadds102025/riskradar/riskradar-api:latest'
timeout: '900s'
