/**
 * Teachers Federal Credit Union — Demo Data
 *
 * Realistic risk monitoring data for E2E testing.
 * This data simulates a mid-size credit union (~$8B assets, 400K members).
 */

// ─── ORGANIZATION CONTEXT ──────────────────────────────────
export const TFCU_TENANT = {
  id: 'demo-tfcu',
  name: 'Teachers Federal Credit Union',
  slug: 'tfcu',
  industry: 'credit_union',
  settings: {
    timezone: 'America/New_York',
    dataRetentionDays: 365,
    enabledDomains: ['hr', 'finance', 'security', 'operations', 'communications'],
    regulatoryFrameworks: ['BSA_AML', 'NCUA', 'GLBA', 'FCRA'],
  },
};

// ─── DEMO USERS ────────────────────────────────────────────
export const DEMO_USERS = [
  { id: 'u-admin', email: 'admin@tfcu.org', name: 'Maria Gonzalez', role: 'admin', title: 'VP of Risk & Compliance' },
  { id: 'u-cco', email: 'compliance@tfcu.org', name: 'David Chen', role: 'compliance_officer', title: 'Chief Compliance Officer' },
  { id: 'u-ciso', email: 'ciso@tfcu.org', name: 'Raj Patel', role: 'ciso', title: 'Chief Information Security Officer' },
  { id: 'u-analyst1', email: 'sarah.kim@tfcu.org', name: 'Sarah Kim', role: 'analyst', title: 'Senior Risk Analyst' },
  { id: 'u-analyst2', email: 'james.wright@tfcu.org', name: 'James Wright', role: 'analyst', title: 'BSA/AML Analyst' },
  { id: 'u-mgr', email: 'linda.thompson@tfcu.org', name: 'Linda Thompson', role: 'manager', title: 'Branch Operations Manager' },
  { id: 'u-auditor', email: 'auditor@tfcu.org', name: 'Robert Martinez', role: 'auditor', title: 'Internal Auditor' },
];

// ─── ALERTS ────────────────────────────────────────────────
export const DEMO_ALERTS = [
  {
    id: 'ALT-2026-1201',
    title: 'Compound Risk: Member Services + Finance — Score 89',
    description: 'Cross-domain risk pattern detected: MSR-4821 processed 7 override transactions totaling $340K during supervisor PTO, combined with after-hours CRM access to member files not associated with active cases.',
    alertType: 'compound_risk',
    severity: 'critical',
    status: 'new',
    compoundScore: 89,
    confidenceScore: 91,
    falsePositiveLikelihood: 'low',
    domains: ['finance', 'security', 'operations'],
    subjectType: 'employee',
    subjectId: 'MSR-4821',
    subjectName: 'Teller Supervisor — Hauppauge Branch',
    assignedTo: 'Sarah Kim',
    time: '23 min ago',
    createdAt: new Date(Date.now() - 23 * 60 * 1000).toISOString(),
    evidenceBrief: {
      summary: 'Member Service Representative MSR-4821 processed 7 wire transfer overrides totaling $340,000 during their direct supervisor\'s PTO window. Combined with after-hours CRM access and 2 newly created beneficiary accounts, this pattern matches FinCEN Advisory 2025-A003 insider threat indicators.',
      evidenceChain: [
        { sequence: 1, timestamp: '2026-03-28T14:23:00Z', description: 'Processed 4 wire transfers >$25K each with manager override bypass', sourceSystem: 'Symitar Core Banking', sourceId: 'WR-78291,78292,78295,78296', signalType: 'override_transaction', significance: 'Override volume 7x monthly baseline. Transfers to 2 newly created beneficiary accounts.' },
        { sequence: 2, timestamp: '2026-03-27T00:00:00Z', description: 'Direct supervisor (Branch Manager K. Johnson) on approved PTO Mar 27-31', sourceSystem: 'UKG HRIS', sourceId: 'PTO-2847', signalType: 'leave_pattern_change', significance: 'Override clustering correlates with supervisor absence window (r=0.94)' },
        { sequence: 3, timestamp: '2026-03-27T22:14:00Z', description: 'Accessed 12 member profiles in CRM at 10:14 PM — none tied to open service requests', sourceSystem: 'Salesforce CRM Audit', sourceId: 'AUD-E9921..E9932', signalType: 'after_hours_access', significance: 'Access pattern outside normal 8:30AM-5PM branch hours. No corresponding service tickets.' },
        { sequence: 4, timestamp: '2026-03-28T09:15:00Z', description: 'Two beneficiary accounts created same day as $85K and $92K transfers', sourceSystem: 'Symitar Core Banking', sourceId: 'BEN-A1104,A1105', signalType: 'new_payee', significance: 'New beneficiary creation proximate to large outbound wires — structuring indicator per BSA guidelines.' },
        { sequence: 5, timestamp: '2026-03-20T00:00:00Z', description: 'Employee overdue on annual BSA/AML compliance training (due Mar 15)', sourceSystem: 'UKG Learning Management', sourceId: 'TRN-4421', signalType: 'training_missed', significance: 'Non-completion of mandatory compliance training elevates insider risk context.' },
      ],
      reasoning: 'This compound alert was triggered by the convergence of 5 signals across 3 risk domains within a 7-day window. The primary concern is the override clustering during supervisor absence — a pattern that matches FinCEN\'s 2025-A003 Advisory on insider threat indicators (specifically red flags 4, 7, and 12). The temporal correlation between the supervisor\'s PTO start and the spike in override transactions is statistically significant (p < 0.005). Additionally, the after-hours CRM access to member profiles unrelated to open cases suggests potential reconnaissance activity. The creation of new beneficiary accounts within hours of large outbound transfers is a classic structuring pattern. The missed BSA training compounds the concern as it suggests either negligence or deliberate avoidance of compliance awareness. NCUA Letter 26-CU-03 specifically highlights this multi-factor pattern as requiring immediate investigation.',
      regulatoryMapping: [
        { regulation: 'BSA/AML', section: 'FinCEN Advisory 2025-A003', description: 'Insider threat red flag indicators 4 (override clustering), 7 (supervisor absence correlation), 12 (new payee proximate to transfers)', relevance: 'direct' },
        { regulation: 'BSA/AML', section: '31 CFR 1020.320', description: 'SAR filing requirements — transactions >$5,000 involving suspected illegal activity', relevance: 'direct' },
        { regulation: 'NCUA', section: 'Letter 26-CU-03', description: 'Credit union insider threat controls — supervisor override monitoring', relevance: 'direct' },
        { regulation: 'GLBA', section: 'Reg P — 12 CFR 1016', description: 'Privacy of consumer financial information — unauthorized access to member records', relevance: 'related' },
      ],
      recommendedActions: [
        { priority: 'immediate', action: 'Suspend override privileges for MSR-4821 and notify Branch Manager K. Johnson' },
        { priority: 'immediate', action: 'Place administrative hold on beneficiary accounts BEN-A1104 and BEN-A1105' },
        { priority: 'within_24h', action: 'BSA Officer (D. Chen) review wire transfers WR-78291, 78292, 78295, 78296' },
        { priority: 'within_72h', action: 'File SAR per 31 CFR 1020.320 — 30-day filing deadline: April 27, 2026' },
        { priority: 'within_week', action: 'Conduct full 90-day transaction review for MSR-4821 across all systems' },
      ],
    },
  },
  {
    id: 'ALT-2026-1198',
    title: 'Data Exfiltration Risk: IT Admin After-Hours Access',
    description: 'IT administrator accessed production member database and exported 2.1GB of data at 11:42 PM. Pattern inconsistent with scheduled maintenance windows.',
    alertType: 'anomaly',
    severity: 'high',
    status: 'under_review',
    compoundScore: 76,
    confidenceScore: 82,
    falsePositiveLikelihood: 'medium',
    domains: ['security', 'operations'],
    subjectType: 'employee',
    subjectId: 'IT-1102',
    subjectName: 'Database Administrator — IT Operations',
    assignedTo: 'Raj Patel',
    time: '2h ago',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'ALT-2026-1195',
    title: 'Risk Trajectory Alert: Loan Officer Score 42 → Projected 74',
    description: 'Accelerating risk trajectory for Loan Officer LO-3847. Unusual loan approval patterns combined with Glassdoor sentiment signals and increased PTO requests.',
    alertType: 'trajectory',
    severity: 'medium',
    status: 'new',
    compoundScore: 56,
    confidenceScore: 74,
    falsePositiveLikelihood: 'medium',
    domains: ['hr', 'finance', 'communications'],
    subjectType: 'employee',
    subjectId: 'LO-3847',
    subjectName: 'Senior Loan Officer — Commack Branch',
    assignedTo: 'James Wright',
    time: '5h ago',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'ALT-2026-1192',
    title: 'AML Override Clustering: Farmingville Branch — 14 Overrides in 3 Days',
    description: 'Branch-level pattern: 14 manager overrides across 4 tellers in the Farmingville branch over 3 days. Transactions cluster just below CTR threshold ($9,500-$9,950).',
    alertType: 'pattern',
    severity: 'high',
    status: 'new',
    compoundScore: 71,
    confidenceScore: 88,
    falsePositiveLikelihood: 'low',
    domains: ['finance'],
    subjectType: 'department',
    subjectId: 'BRANCH-FV',
    subjectName: 'Farmingville Branch',
    assignedTo: null,
    time: '8h ago',
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
  },
  {
    id: 'ALT-2026-1188',
    title: 'Expense Anomaly: Benford Distribution Violation in Travel Claims',
    description: 'VP-level expense reports show statistically significant deviation from expected Benford distribution. First-digit analysis flags potential fabrication.',
    alertType: 'anomaly',
    severity: 'medium',
    status: 'confirmed',
    compoundScore: 48,
    confidenceScore: 79,
    falsePositiveLikelihood: 'medium',
    domains: ['finance', 'hr'],
    subjectType: 'employee',
    subjectId: 'VP-2156',
    subjectName: 'VP of Member Services',
    assignedTo: 'Sarah Kim',
    time: '1d ago',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'ALT-2026-1185',
    title: 'Privileged Access Anomaly: Service Account Credential Sharing',
    description: 'Shared service account SVCACCT-CORE detected logging in from 3 different geographic locations within 15 minutes. Credential compromise suspected.',
    alertType: 'anomaly',
    severity: 'critical',
    status: 'under_review',
    compoundScore: 83,
    confidenceScore: 95,
    falsePositiveLikelihood: 'low',
    domains: ['security'],
    subjectType: 'service_account',
    subjectId: 'SVCACCT-CORE',
    subjectName: 'Core Banking Service Account',
    assignedTo: 'Raj Patel',
    time: '3h ago',
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'ALT-2026-1180',
    title: 'Member Complaint Surge: Online Banking Platform — 340% Increase',
    description: 'Sentiment analysis detects 340% increase in negative member complaints about online banking. Correlates with recent platform update deployment.',
    alertType: 'trend',
    severity: 'medium',
    status: 'dismissed',
    compoundScore: 35,
    confidenceScore: 92,
    falsePositiveLikelihood: 'high',
    domains: ['communications', 'operations'],
    subjectType: 'system',
    subjectId: 'SYS-OLB',
    subjectName: 'Online Banking Platform',
    assignedTo: null,
    time: '2d ago',
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  // ── IC3 2025: BEC Defense ─────────────────────────────────
  {
    id: 'ALT-2026-1210',
    title: 'BEC Attack: CFO Wire Request — Writing Style Deviation Detected',
    description: 'Email from CFO account requesting $285K wire to new vendor account shows 94% writing style deviation from baseline. Sent at 11:47 PM from unfamiliar device in Eastern Europe. Vendor banking details changed 2 hours prior.',
    alertType: 'compound_risk',
    severity: 'critical',
    status: 'new',
    compoundScore: 92,
    confidenceScore: 96,
    falsePositiveLikelihood: 'low',
    domains: ['bec', 'finance', 'security'],
    subjectType: 'external_threat',
    subjectId: 'BEC-EXT-0041',
    subjectName: 'CFO Email Compromise — Impersonation',
    assignedTo: 'Sarah Kim',
    time: '12 min ago',
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    evidenceBrief: {
      summary: 'A Business Email Compromise attack targeting CFO email account detected via writing style analysis, device fingerprint mismatch, and vendor payment change correlation. Pattern matches FBI IC3 BEC typology — $3B+ in annual losses.',
      evidenceChain: [
        { sequence: 1, timestamp: '2026-04-06T23:47:00Z', description: 'CFO email requests urgent $285K wire transfer to "updated" vendor account. Writing style scores 94% deviation from learned CFO baseline.', sourceSystem: 'Microsoft 365 — Email Analytics', sourceId: 'MSG-2026-EML-88421', signalType: 'writing_style_deviation', significance: 'Writing cadence, vocabulary, and formatting deviate significantly from 18-month CFO email baseline model.' },
        { sequence: 2, timestamp: '2026-04-06T23:45:00Z', description: 'Email sent from IP 185.xx.xx.42 (Kyiv, Ukraine) — device not in CFO known device registry', sourceSystem: 'Azure AD', sourceId: 'AUTH-2026-99812', signalType: 'unfamiliar_device_auth', significance: 'CFO has never authenticated from this geography or device.' },
        { sequence: 3, timestamp: '2026-04-06T21:30:00Z', description: 'Vendor Acme Corp banking details updated to new account 2 hours before wire request', sourceSystem: 'Workday Financials', sourceId: 'VND-CHG-4418', signalType: 'vendor_payment_change', significance: 'Vendor banking details change followed by urgent payment request — classic BEC sequence per FBI IC3.' },
        { sequence: 4, timestamp: '2026-04-06T23:47:00Z', description: 'Wire request marked "URGENT — process before end of business" — pressure language detected', sourceSystem: 'RiskRadar NLP Engine', sourceId: 'NLP-URGENCY-0092', signalType: 'urgency_pressure', significance: 'Urgency language is a primary BEC social engineering tactic.' },
      ],
      reasoning: 'This alert represents a textbook Business Email Compromise (BEC) attack as classified by FBI IC3 2025. The attack combines email account compromise with vendor impersonation — the two most costly BEC variants. Four signals converge: (1) writing style deviation from the CFO\'s learned baseline, (2) authentication from an unfamiliar foreign device, (3) vendor banking detail change immediately preceding the wire request, and (4) urgency pressure language. The FBI IC3 2025 report documents $3B+ in BEC losses, making this the second-costliest cybercrime category. RiskRadar\'s BEC Analyzer engine detected this via cross-correlation of email metadata, device fingerprinting, vendor baseline monitoring, and NLP urgency detection.',
      regulatoryMapping: [
        { regulation: 'FBI IC3', section: 'BEC Advisory 2025', description: 'Business Email Compromise — second costliest cybercrime at $3B+ annually', relevance: 'direct' },
        { regulation: 'BSA/AML', section: '31 CFR 1020.320', description: 'SAR filing for suspected fraud involving wire transfers', relevance: 'direct' },
        { regulation: 'GLBA', section: 'Reg P — 12 CFR 1016', description: 'Account security and unauthorized access', relevance: 'related' },
      ],
      recommendedActions: [
        { priority: 'immediate', action: 'BLOCK wire transfer to new vendor account. Initiate out-of-band CFO verification via pre-registered phone number.' },
        { priority: 'immediate', action: 'Force password reset and session revocation on CFO email account. Enable conditional access geo-fencing.' },
        { priority: 'within_24h', action: 'Verify Acme Corp banking details through known vendor contact (not from the compromised email thread).' },
        { priority: 'within_72h', action: 'Conduct organization-wide BEC awareness alert. Review all vendor payment changes in last 30 days.' },
      ],
    },
  },
  // ── IC3 2025: Crypto Fraud ────────────────────────────────
  {
    id: 'ALT-2026-1212',
    title: 'Crypto Fraud: Pig Butchering Pattern — Member Account MBR-9923',
    description: 'Member showing classic pig butchering escalation pattern: 5 escalating crypto transfers ($2K → $5K → $15K → $45K → $120K) over 6 weeks to wallet flagged by Chainalysis as connected to known romance scam ring.',
    alertType: 'pattern',
    severity: 'high',
    status: 'new',
    compoundScore: 81,
    confidenceScore: 89,
    falsePositiveLikelihood: 'low',
    domains: ['crypto', 'finance'],
    subjectType: 'member_account',
    subjectId: 'MBR-9923',
    subjectName: 'Member Account — Potential Fraud Victim',
    assignedTo: 'James Wright',
    time: '45 min ago',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    evidenceBrief: {
      summary: 'Member MBR-9923 exhibits a pig butchering (crypto investment scam) victimization pattern. Escalating transfers to high-risk wallet address flagged by Chainalysis. FBI IC3 2025 reports $8.6B in investment fraud losses — crypto pig butchering is the dominant vector.',
      evidenceChain: [
        { sequence: 1, timestamp: '2026-02-22T10:00:00Z', description: 'Initial $2,000 ACH transfer to Coinbase, then on-chain transfer to wallet 0x7a3f...', sourceSystem: 'Symitar Core Banking + Chainalysis', sourceId: 'ACH-44210', signalType: 'crypto_transfer_escalation', significance: 'First of 5 escalating transfers — seeding phase of pig butchering pattern.' },
        { sequence: 2, timestamp: '2026-04-05T14:00:00Z', description: 'Latest transfer: $120,000 ACH to exchange, immediate withdrawal to same wallet cluster', sourceSystem: 'Symitar + Chainalysis KYT', sourceId: 'ACH-44892', signalType: 'crypto_transfer_escalation', significance: 'Transfer 60x initial amount — exponential escalation matches grooming pattern.' },
        { sequence: 3, timestamp: '2026-04-06T00:00:00Z', description: 'Destination wallet 0x7a3f... risk score: 91/100 — linked to Southeast Asia romance scam ring per Chainalysis', sourceSystem: 'Chainalysis KYT', sourceId: 'WALLET-RISK-7a3f', signalType: 'high_risk_wallet', significance: 'Wallet associated with known pig butchering operation (Operation Level Up targets).' },
        { sequence: 4, timestamp: '2026-04-05T00:00:00Z', description: 'Member savings account depleted from $340K to $152K in 6 weeks', sourceSystem: 'Symitar Core Banking', sourceId: 'ACCT-DEPLETION-9923', signalType: 'rapid_asset_depletion', significance: 'Account depletion rate consistent with fraud victimization — not normal spending pattern.' },
      ],
      reasoning: 'This pattern matches the FBI IC3 2025 pig butchering typology — the dominant investment fraud vector responsible for the majority of $8.6B in investment fraud losses. The escalating transfer pattern (seeding, grooming, harvesting phases) combined with Chainalysis wallet risk scoring provides high-confidence detection. RiskRadar identified this through cross-correlation of banking transaction data with blockchain analytics, detecting the characteristic exponential escalation and linking destination wallets to known fraud operations.',
      regulatoryMapping: [
        { regulation: 'FBI IC3', section: 'Investment Fraud Advisory 2025', description: 'Investment fraud — $8.6B losses, #1 costliest cybercrime category', relevance: 'direct' },
        { regulation: 'FinCEN', section: '2025-G001 — Crypto Advisory', description: 'Virtual asset transaction monitoring for fraud patterns', relevance: 'direct' },
        { regulation: 'BSA/AML', section: '31 CFR 1020.320', description: 'SAR filing for suspected fraud-related transactions', relevance: 'direct' },
      ],
      recommendedActions: [
        { priority: 'immediate', action: 'Contact member MBR-9923 for welfare check — potential active fraud victim. Use FBI IC3 Operation Level Up notification protocol.' },
        { priority: 'immediate', action: 'Place temporary hold on further ACH transfers to crypto exchanges per FINRA Rule 2165 (adapted for credit union use).' },
        { priority: 'within_24h', action: 'File SAR with FinCEN — crypto investment fraud indicator. Reference FBI Operation Level Up.' },
        { priority: 'within_72h', action: 'Report destination wallet to IC3 Recovery Asset Team (RAT) for potential fund recovery.' },
      ],
    },
  },
  // ── IC3 2025: Ransomware Exposure ─────────────────────────
  {
    id: 'ALT-2026-1215',
    title: 'Ransomware Exposure: Critical Attack Surface Score — MITRE ATT&CK Match',
    description: 'Organization ransomware exposure score jumped to 74/100. 3 unpatched critical CVEs match active exploitation by LockBit 4.0 group. External attack surface scan detected exposed RDP on 2 branch servers.',
    alertType: 'anomaly',
    severity: 'high',
    status: 'new',
    compoundScore: 74,
    confidenceScore: 86,
    falsePositiveLikelihood: 'low',
    domains: ['security', 'ransomware'],
    subjectType: 'infrastructure',
    subjectId: 'INFRA-SURFACE',
    subjectName: 'Organizational Attack Surface',
    assignedTo: 'Raj Patel',
    time: '1h ago',
    createdAt: new Date(Date.now() - 3600 * 1000).toISOString(),
  },
  // ── IC3 2025: AI-Generated Phishing ───────────────────────
  {
    id: 'ALT-2026-1218',
    title: 'AI-Enabled Phishing Campaign: 47 AI-Crafted Emails Targeting Staff',
    description: 'AI threat detection identified 47 AI-generated spear-phishing emails targeting TFCU staff over 72 hours. Emails use personalized context from scraped LinkedIn data with LLM-generated text bypassing traditional spam filters.',
    alertType: 'pattern',
    severity: 'high',
    status: 'under_review',
    compoundScore: 68,
    confidenceScore: 91,
    falsePositiveLikelihood: 'low',
    domains: ['ai_threat', 'security', 'communications'],
    subjectType: 'external_threat',
    subjectId: 'AI-PHISH-CAMP-0012',
    subjectName: 'AI-Generated Phishing Campaign',
    assignedTo: 'Raj Patel',
    time: '3h ago',
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  // ── IC3 2025: Vendor Supply Chain Risk ────────────────────
  {
    id: 'ALT-2026-1220',
    title: 'Supply Chain Risk: Critical Vendor SecurityScorecard Drop — Acme Payments',
    description: 'Key payment processor Acme Payments\' security rating dropped from A to C (SecurityScorecard). Recent dark web credential dump includes 2,400 Acme employee credentials. Acme processes 40% of TFCU ACH volume.',
    alertType: 'trend',
    severity: 'medium',
    status: 'new',
    compoundScore: 62,
    confidenceScore: 78,
    falsePositiveLikelihood: 'medium',
    domains: ['vendor_risk', 'security'],
    subjectType: 'vendor',
    subjectId: 'VND-ACME-PAY',
    subjectName: 'Acme Payments (Critical Vendor)',
    assignedTo: null,
    time: '6h ago',
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
];

// ─── CASES ─────────────────────────────────────────────────
export const DEMO_CASES = [
  {
    id: 'CSE-2026-001',
    title: 'Insider Transaction Fraud — Hauppauge Branch Teller Supervisor',
    status: 'investigating',
    priority: 'critical',
    subjectId: 'MSR-4821',
    assignee: 'Sarah Kim',
    alerts: 3,
    comments: 12,
    slaStatus: 'on_track',
    slaDeadline: '2026-04-08',
    created: '2h ago',
    description: 'Investigation into potential insider-facilitated wire fraud. MSR-4821 processed $340K in override wire transfers during supervisor absence with links to newly created beneficiary accounts.',
  },
  {
    id: 'CSE-2026-002',
    title: 'Potential Data Exfiltration — IT Database Admin',
    status: 'pending_legal',
    priority: 'high',
    subjectId: 'IT-1102',
    assignee: 'Raj Patel',
    alerts: 2,
    comments: 8,
    slaStatus: 'at_risk',
    slaDeadline: '2026-04-05',
    created: '1d ago',
    description: 'Database administrator exported 2.1GB of member data after hours. Legal review requested to determine if data falls under GLBA protected categories.',
  },
  {
    id: 'CSE-2026-003',
    title: 'Structuring Pattern — Farmingville Branch',
    status: 'open',
    priority: 'high',
    subjectId: 'BRANCH-FV',
    assignee: 'James Wright',
    alerts: 4,
    comments: 5,
    slaStatus: 'on_track',
    slaDeadline: '2026-04-12',
    created: '8h ago',
    description: 'Branch-level investigation into possible structuring. 14 overrides across 4 tellers with transactions clustering at $9,500-$9,950 (just below CTR threshold).',
  },
  {
    id: 'CSE-2026-004',
    title: 'Credential Compromise — Core Banking Service Account',
    status: 'action_required',
    priority: 'critical',
    subjectId: 'SVCACCT-CORE',
    assignee: 'Raj Patel',
    alerts: 1,
    comments: 15,
    slaStatus: 'breached',
    slaDeadline: '2026-03-29',
    created: '3d ago',
    description: 'Service account credential may be compromised — simultaneous logins from 3 geographies. Immediate rotation required. Assessing blast radius of potential unauthorized access.',
  },
  {
    id: 'CSE-2026-005',
    title: 'Expense Fraud Review — VP Member Services',
    status: 'pending_review',
    priority: 'medium',
    subjectId: 'VP-2156',
    assignee: 'Linda Thompson',
    alerts: 1,
    comments: 4,
    slaStatus: 'on_track',
    slaDeadline: '2026-04-15',
    created: '1d ago',
    description: 'Benford analysis flagged potential expense fabrication in travel claims. Awaiting manager review of supporting documentation.',
  },
  {
    id: 'CSE-2025-089',
    title: 'Former Employee Unauthorized Access — Closed',
    status: 'closed_confirmed',
    priority: 'high',
    subjectId: 'EX-EMP-7744',
    assignee: 'Sarah Kim',
    alerts: 2,
    comments: 22,
    slaStatus: 'met',
    slaDeadline: '2026-02-15',
    created: '6w ago',
    description: 'Confirmed unauthorized access by former employee using active credentials 3 weeks post-termination. Access revoked, SAR filed, referred to law enforcement.',
  },
];

// ─── RISK SCORES ───────────────────────────────────────────
export const DEMO_RISK_SCORES = [
  { id: 'MSR-4821', type: 'employee', score: 89, trajectory: 'accelerating', domains: { finance: 92, security: 71, operations: 68 }, change: '+31', dept: 'Member Services — Hauppauge' },
  { id: 'IT-1102', type: 'employee', score: 76, trajectory: 'accelerating', domains: { security: 85, operations: 62 }, change: '+22', dept: 'IT Operations' },
  { id: 'BRANCH-FV', type: 'department', score: 71, trajectory: 'stable', domains: { finance: 71, compliance: 65 }, change: '+5', dept: 'Farmingville Branch' },
  { id: 'LO-3847', type: 'employee', score: 56, trajectory: 'accelerating', domains: { finance: 62, hr: 58, communications: 44 }, change: '+18', dept: 'Lending — Commack' },
  { id: 'SVCACCT-CORE', type: 'service_account', score: 83, trajectory: 'accelerating', domains: { security: 95 }, change: '+83', dept: 'Core Banking Systems' },
  { id: 'VP-2156', type: 'employee', score: 48, trajectory: 'stable', domains: { finance: 48, hr: 32 }, change: '+4', dept: 'Member Services — HQ' },
  { id: 'TLR-5500', type: 'employee', score: 28, trajectory: 'declining', domains: { finance: 28 }, change: '-12', dept: 'Teller — Centereach' },
  { id: 'MKT-3310', type: 'employee', score: 15, trajectory: 'stable', domains: { communications: 15 }, change: '-2', dept: 'Marketing' },
];

// ─── SIGNALS SUMMARY ──────────────────────────────────────
export const DEMO_SIGNAL_STATS = {
  total24h: 3_187,
  byDomain: {
    finance: 682,
    security: 524,
    hr: 312,
    operations: 445,
    communications: 378,
    crypto: 214,
    vendor_risk: 156,
    ai_threat: 98,
    bec: 186,
    ransomware: 192,
  },
};

// ─── KPI OVERVIEW ─────────────────────────────────────────
export const DEMO_KPIS = {
  activeAlerts: { value: 12, change: '+5', trend: 'up' as const },
  openCases: { value: 8, change: '+3', trend: 'up' as const },
  highRiskSubjects: { value: 6, change: '+2', trend: 'up' as const },
  signals24h: { value: '3,187', change: '+36%', trend: 'up' as const },
  ic3ThreatScore: { value: 78, change: '+12', trend: 'up' as const },
};

export const DEMO_RISK_DISTRIBUTION = {
  critical: 3,
  high: 5,
  medium: 6,
  low: 5,
};

// ─── POLICIES ──────────────────────────────────────────────
export const DEMO_POLICIES = [
  { id: 'POL-001', name: 'Wire Transfer Override Monitoring', domain: 'finance', type: 'threshold', status: 'active', regulatory: 'BSA/AML — 31 CFR 1020', version: 3, approvedBy: 'David Chen', description: 'Monitor all wire transfer overrides >$10K. Escalate when 3+ overrides occur within a 7-day window or during supervisor absence.' },
  { id: 'POL-002', name: 'After-Hours System Access', domain: 'security', type: 'behavioral', status: 'active', regulatory: 'GLBA — Reg P', version: 2, approvedBy: 'Raj Patel', description: 'Flag access to production systems outside business hours (6PM-7AM) when not associated with approved maintenance tickets.' },
  { id: 'POL-003', name: 'CTR Structuring Detection', domain: 'finance', type: 'pattern', status: 'active', regulatory: 'BSA/AML — 31 CFR 1010.311', version: 5, approvedBy: 'David Chen', description: 'Detect transaction patterns that cluster within 5% of CTR reporting threshold ($10,000). Alert on 3+ sub-threshold transactions from same member within 48h.' },
  { id: 'POL-004', name: 'Employee Attrition Risk Signals', domain: 'hr', type: 'behavioral', status: 'active', regulatory: null, version: 1, approvedBy: 'Maria Gonzalez', description: 'Monitor for combinations of: resume update signals, increased PTO requests, Glassdoor review sentiment, and declining engagement scores.' },
  { id: 'POL-005', name: 'Privileged Account Monitoring', domain: 'security', type: 'threshold', status: 'active', regulatory: 'NCUA — Part 748', version: 4, approvedBy: 'Raj Patel', description: 'Monitor all privileged service accounts for concurrent sessions, geographic anomalies, and access outside approved IP ranges.' },
  { id: 'POL-006', name: 'Vendor Payment Anomaly Detection', domain: 'finance', type: 'anomaly', status: 'pending_approval', regulatory: 'SOX 404', version: 1, approvedBy: null, description: 'Use Benford analysis on vendor payment first digits. Flag when distribution deviates >2 standard deviations from expected frequency.' },
  { id: 'POL-007', name: 'Member Complaint Sentiment Analysis', domain: 'communications', type: 'trend', status: 'active', regulatory: 'CFPB — UDAAP', version: 2, approvedBy: 'Maria Gonzalez', description: 'NLP analysis of member complaints across channels. Escalate when negative sentiment increases >200% over rolling 7-day average.' },
  { id: 'POL-008', name: 'Loan Approval Authority Monitoring', domain: 'finance', type: 'threshold', status: 'draft', regulatory: 'NCUA — Part 723', version: 1, approvedBy: null, description: 'Monitor loan approvals against officer authority limits. Flag any approval within 10% of limit or approvals for related members.' },
  { id: 'POL-009', name: 'BEC Email Behavior Analytics', domain: 'bec', type: 'behavioral', status: 'active', regulatory: 'FBI IC3 — BEC Advisory 2025', version: 1, approvedBy: 'David Chen', description: 'ML-based email communication pattern analysis. Flag deviations in writing style, sender behavior, and request types. Trigger MFA verification on urgent wire transfer requests from anomalous patterns.' },
  { id: 'POL-010', name: 'Vendor Payment Impersonation Detection', domain: 'bec', type: 'pattern', status: 'active', regulatory: 'SOX 404 / FBI IC3', version: 1, approvedBy: 'David Chen', description: 'Cross-reference incoming invoices and payment instructions against vendor baseline profiles. Flag any changes to banking details, invoice format deviations, or new payment routing.' },
  { id: 'POL-011', name: 'Cryptocurrency Transaction Monitoring', domain: 'crypto', type: 'anomaly', status: 'active', regulatory: 'FinCEN — Travel Rule / BSA', version: 1, approvedBy: 'David Chen', description: 'Monitor crypto wallet transactions for patterns matching pig butchering, mixer usage, or sanctioned entity transfers. Real-time risk scoring via Chainalysis integration.' },
  { id: 'POL-012', name: 'Crypto Wallet Risk Scoring', domain: 'crypto', type: 'threshold', status: 'active', regulatory: 'FinCEN 2025-G001 / OFAC SDN', version: 1, approvedBy: 'David Chen', description: 'Continuous risk scoring of crypto wallet addresses. Flag wallets associated with known fraud rings, mixer services, or OFAC-sanctioned entities. Block transactions scoring above 85.' },
  { id: 'POL-013', name: 'Ransomware Exposure Assessment', domain: 'security', type: 'anomaly', status: 'active', regulatory: 'NIST CSF 2.0 / CISA KEV', version: 2, approvedBy: 'Raj Patel', description: 'Continuous attack surface monitoring mapped to ransomware group TTPs (MITRE ATT&CK). Score based on exposed services, unpatched CVEs, dark web intelligence, and credential leak exposure.' },
  { id: 'POL-014', name: 'AI-Generated Phishing Detection', domain: 'ai_threat', type: 'behavioral', status: 'active', regulatory: 'FBI IC3 — AI Threat Advisory 2025', version: 1, approvedBy: 'Raj Patel', description: 'Detect AI-generated phishing emails using linguistic analysis, metadata anomalies, and known AI-crafted template fingerprints. Correlate with OSINT feeds on emerging AI attack tools.' },
  { id: 'POL-015', name: 'Supply Chain Vendor Risk Monitoring', domain: 'vendor_risk', type: 'trend', status: 'active', regulatory: 'NIST SP 800-161r1', version: 1, approvedBy: 'Raj Patel', description: 'Continuous monitoring of third-party vendor security posture. Score and alert on changes in vendor risk profiles, breach disclosures, CVE exposure, and compliance certification lapses.' },
];

// ─── INTEGRATIONS ──────────────────────────────────────────
export const DEMO_INTEGRATIONS = [
  { id: 'int-1', name: 'Symitar Core Banking', provider: 'Jack Henry', type: 'core_banking', status: 'connected', health: 'healthy', lastSync: '2 min ago', signals: 'Transactions, accounts, wires, ACH' },
  { id: 'int-2', name: 'UKG Pro (HRIS)', provider: 'UKG', type: 'hris', status: 'connected', health: 'healthy', lastSync: '15 min ago', signals: 'Attendance, PTO, training, org changes' },
  { id: 'int-3', name: 'Microsoft 365', provider: 'Microsoft', type: 'productivity', status: 'connected', health: 'healthy', lastSync: '5 min ago', signals: 'Email metadata, Teams activity, SharePoint access' },
  { id: 'int-4', name: 'Azure Active Directory', provider: 'Microsoft', type: 'identity', status: 'connected', health: 'healthy', lastSync: '1 min ago', signals: 'Authentication logs, MFA events, access patterns' },
  { id: 'int-5', name: 'Salesforce CRM', provider: 'Salesforce', type: 'crm', status: 'connected', health: 'degraded', lastSync: '45 min ago', signals: 'Member interactions, case management, audit trail' },
  { id: 'int-6', name: 'Splunk SIEM', provider: 'Splunk', type: 'siem', status: 'connected', health: 'healthy', lastSync: '1 min ago', signals: 'Security events, network logs, endpoint telemetry' },
  { id: 'int-7', name: 'Jira Service Management', provider: 'Atlassian', type: 'itsm', status: 'connected', health: 'healthy', lastSync: '10 min ago', signals: 'Change requests, incidents, maintenance windows' },
  { id: 'int-8', name: 'Workday Financials', provider: 'Workday', type: 'erp', status: 'pending', health: 'unknown', lastSync: 'Never', signals: 'Expense reports, vendor payments, GL entries' },
  { id: 'int-9', name: 'Chainalysis KYT', provider: 'Chainalysis', type: 'blockchain_analytics', status: 'connected', health: 'healthy', lastSync: '3 min ago', signals: 'Wallet risk scores, transaction graphs, mixer detection, sanctions screening' },
  { id: 'int-10', name: 'MITRE ATT&CK Feed', provider: 'MITRE', type: 'threat_intelligence', status: 'connected', health: 'healthy', lastSync: '1h ago', signals: 'Ransomware TTPs, threat actor profiles, technique mappings' },
  { id: 'int-11', name: 'AI Threat Intelligence', provider: 'RiskRadar OSINT', type: 'ai_threat_feed', status: 'connected', health: 'healthy', lastSync: '30 min ago', signals: 'AI attack patterns, deepfake toolkits, AI phishing templates' },
  { id: 'int-12', name: 'SecurityScorecard', provider: 'SecurityScorecard', type: 'vendor_risk', status: 'connected', health: 'healthy', lastSync: '6h ago', signals: 'Vendor security ratings, breach alerts, compliance status' },
  { id: 'int-13', name: 'TRM Labs', provider: 'TRM Labs', type: 'blockchain_analytics', status: 'connected', health: 'healthy', lastSync: '5 min ago', signals: 'Cross-chain tracing, DeFi risk, sanctions compliance' },
];

// ─── AUDIT LOG ─────────────────────────────────────────────
export const DEMO_AUDIT_LOGS = [
  { id: 'aud-1', timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(), actor: 'Sarah Kim', action: 'alert.viewed', resource: 'Alert ALT-2026-1201', details: 'Viewed critical compound risk alert' },
  { id: 'aud-2', timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(), actor: 'System (Fusion Engine)', action: 'alert.created', resource: 'Alert ALT-2026-1201', details: 'Auto-generated compound risk alert — score 89, 5 signals fused' },
  { id: 'aud-3', timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(), actor: 'Raj Patel', action: 'alert.status_changed', resource: 'Alert ALT-2026-1185', details: 'Status changed: new → under_review' },
  { id: 'aud-4', timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(), actor: 'James Wright', action: 'case.comment_added', resource: 'Case CSE-2026-003', details: 'Added investigation note re: Farmingville branch structuring pattern' },
  { id: 'aud-5', timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(), actor: 'System (SAR Generator)', action: 'sar.draft_created', resource: 'SAR-2026-001', details: 'Auto-generated SAR draft for Case CSE-2026-001 — filing deadline Apr 27' },
  { id: 'aud-6', timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(), actor: 'David Chen', action: 'policy.approved', resource: 'Policy POL-007', details: 'Approved v2 of Member Complaint Sentiment Analysis policy' },
  { id: 'aud-7', timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(), actor: 'Maria Gonzalez', action: 'user.login', resource: 'Session', details: 'Successful login from 10.0.1.45 (HQ Network)' },
  { id: 'aud-8', timestamp: new Date(Date.now() - 8 * 3600 * 1000).toISOString(), actor: 'System (Regulatory Watchdog)', action: 'regulatory.update_detected', resource: 'NCUA Letter 26-CU-05', details: 'New NCUA guidance detected — AI/ML in credit union risk monitoring' },
];

// ─── AGENT STATUS ─────────────────────────────────────────
export const DEMO_AGENTS = [
  { id: 'agent-fin', name: 'Finance Collector', team: 'Collection', status: 'running', lastRun: '2 min ago', signals: 682, health: 'healthy' },
  { id: 'agent-sec', name: 'Security Collector', team: 'Collection', status: 'running', lastRun: '1 min ago', signals: 524, health: 'healthy' },
  { id: 'agent-hr', name: 'HR Collector', team: 'Collection', status: 'running', lastRun: '15 min ago', signals: 312, health: 'healthy' },
  { id: 'agent-ops', name: 'Operations Collector', team: 'Collection', status: 'running', lastRun: '5 min ago', signals: 445, health: 'healthy' },
  { id: 'agent-comm', name: 'Communications Collector', team: 'Collection', status: 'running', lastRun: '10 min ago', signals: 378, health: 'healthy' },
  { id: 'agent-fusion', name: 'Fusion Engine', team: 'Analysis', status: 'running', lastRun: '23 min ago', signals: null, health: 'healthy' },
  { id: 'agent-reg', name: 'Regulatory Watchdog', team: 'Analysis', status: 'running', lastRun: '6h ago', signals: null, health: 'healthy' },
  { id: 'agent-traj', name: 'Trajectory Engine', team: 'Analysis', status: 'running', lastRun: '1h ago', signals: null, health: 'healthy' },
  { id: 'agent-bias', name: 'Bias Check', team: 'Analysis', status: 'idle', lastRun: '4h ago', signals: null, health: 'healthy' },
  { id: 'agent-router', name: 'Alert Router', team: 'Response', status: 'running', lastRun: '23 min ago', signals: null, health: 'healthy' },
  { id: 'agent-notify', name: 'Notification Agent', team: 'Response', status: 'running', lastRun: '23 min ago', signals: null, health: 'healthy' },
  { id: 'agent-sar', name: 'SAR Generator', team: 'Response', status: 'idle', lastRun: '3h ago', signals: null, health: 'healthy' },
  // ── IC3 2025 Enhancement Agents ─────────────────────────
  { id: 'agent-crypto', name: 'Crypto Fraud Detector', team: 'Analysis', status: 'running', lastRun: '3 min ago', signals: 214, health: 'healthy' },
  { id: 'agent-bec', name: 'BEC Analyzer', team: 'Analysis', status: 'running', lastRun: '12 min ago', signals: 186, health: 'healthy' },
  { id: 'agent-aithreat', name: 'AI Threat Intel', team: 'Analysis', status: 'running', lastRun: '30 min ago', signals: 98, health: 'healthy' },
  { id: 'agent-vendor', name: 'Vendor Risk Monitor', team: 'Analysis', status: 'running', lastRun: '6h ago', signals: 156, health: 'healthy' },
  { id: 'agent-ransomware', name: 'Ransomware Exposure Engine', team: 'Analysis', status: 'running', lastRun: '1h ago', signals: 192, health: 'healthy' },
];

// ─── FBI IC3 2025 THREAT LANDSCAPE DATA ──────────────────
export const IC3_THREAT_DATA = {
  reportYear: 2025,
  totalComplaints: 1_000_000,
  totalLosses: 20_000_000_000,
  topThreats: [
    { category: 'Investment Fraud', losses: 8_600_000_000, complaints: 100_000, trend: '+33%', priority: 'P0', riskRadarModule: 'Crypto Fraud Radar', moduleStatus: 'active' as const },
    { category: 'Crypto Fraud', losses: 7_200_000_000, complaints: 80_000, trend: '+45%', priority: 'P0', riskRadarModule: 'Crypto Fraud Radar', moduleStatus: 'active' as const },
    { category: 'Elder Fraud (60+)', losses: 7_700_000_000, complaints: 150_000, trend: '+37%', priority: 'P1', riskRadarModule: 'Insider Detection (employee-side)', moduleStatus: 'partial' as const },
    { category: 'Business Email Compromise', losses: 3_000_000_000, complaints: 35_000, trend: '+12%', priority: 'P0', riskRadarModule: 'BEC Defense Suite', moduleStatus: 'active' as const },
    { category: 'Tech Support Fraud', losses: 2_100_000_000, complaints: 50_000, trend: '+18%', priority: 'P1', riskRadarModule: 'N/A — Out of scope', moduleStatus: 'not_applicable' as const },
    { category: 'AI-Enabled Scams', losses: 893_000_000, complaints: 22_364, trend: 'NEW', priority: 'P0', riskRadarModule: 'AI Threat Intel Feed', moduleStatus: 'active' as const },
    { category: 'Ransomware', losses: 500_000_000, complaints: 10_000, trend: '+22%', priority: 'P1', riskRadarModule: 'Ransomware Exposure Engine', moduleStatus: 'active' as const },
  ],
  organizationExposure: {
    overallScore: 78,
    coveragePercentage: 85,
    activeModules: 5,
    totalModules: 7,
    gapAreas: ['Elder Fraud (B2C — outside scope)', 'Tech Support Fraud (outside scope)'],
    coveredThreats: ['Investment/Crypto Fraud', 'BEC', 'AI-Enabled Scams', 'Ransomware', 'Supply Chain Risk'],
  },
  weeklyTrend: [
    { week: 'W10', score: 62 },
    { week: 'W11', score: 65 },
    { week: 'W12', score: 68 },
    { week: 'W13', score: 72 },
    { week: 'W14', score: 78 },
  ],
};

// ─── VENDOR RISK SCORES ──────────────────────────────────
export const DEMO_VENDOR_RISKS = [
  { id: 'VND-ACME-PAY', name: 'Acme Payments', category: 'Payment Processor', riskScore: 72, previousScore: 45, trend: 'accelerating', securityRating: 'C', previousRating: 'A', criticalFindings: 3, lastAssessed: '6h ago', dataAccess: 'ACH transactions, member PII', businessImpact: 'critical' },
  { id: 'VND-CLOUDHOST', name: 'CloudHost Pro', category: 'Infrastructure', riskScore: 28, previousScore: 25, trend: 'stable', securityRating: 'A', previousRating: 'A', criticalFindings: 0, lastAssessed: '1d ago', dataAccess: 'Server hosting, backup storage', businessImpact: 'critical' },
  { id: 'VND-MAILSERV', name: 'SecureMail Corp', category: 'Email Security', riskScore: 15, previousScore: 18, trend: 'declining', securityRating: 'A+', previousRating: 'A', criticalFindings: 0, lastAssessed: '2d ago', dataAccess: 'Email routing, spam filtering', businessImpact: 'high' },
  { id: 'VND-PRINTCO', name: 'PrintCo Services', category: 'Document Services', riskScore: 41, previousScore: 38, trend: 'stable', securityRating: 'B', previousRating: 'B', criticalFindings: 1, lastAssessed: '3d ago', dataAccess: 'Member statements, notices', businessImpact: 'medium' },
];
